/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
*/

import React, { useState, useEffect, useCallback } from 'react';
import { streamDefinition } from './services/geminiService';
import ContentDisplay from './components/ContentDisplay';
import SearchBar from './components/SearchBar';
import LoadingSkeleton from './components/LoadingSkeleton';

const App: React.FC = () => {
  const [currentTopic, setCurrentTopic] = useState<string>('Hypertext');
  const [content, setContent] = useState<string>('');
  const [isLoading, setIsLoading] = useState<boolean>(true);
  const [error, setError] = useState<string | null>(null);
  const [generationTime, setGenerationTime] = useState<number | null>(null);
  const [language, setLanguage] = useState<string>('English');
  
  useEffect(() => {
    if (!currentTopic) return;
    
    // Skip fetching if we are not loading.
    // However, if language changes, we typically want to refresh.
    // We'll rely on isLoading being true to permit fetching.
    if (content && !isLoading) {
        return; 
    }

    let isCancelled = false;

    const fetchContent = async () => {
      setIsLoading(true);
      setError(null);
      setContent(''); 
      setGenerationTime(null);
      const startTime = performance.now();

      let accumulatedContent = '';
      try {
        for await (const chunk of streamDefinition(currentTopic, language)) {
          if (isCancelled) break;
          
          if (chunk.startsWith('Error:')) {
            throw new Error(chunk);
          }
          accumulatedContent += chunk;
          if (!isCancelled) {
            setContent(accumulatedContent);
          }
        }
      } catch (e: unknown) {
        if (!isCancelled) {
          const errorMessage = e instanceof Error ? e.message : 'An unknown error occurred';
          setError(errorMessage);
          setContent('');
          console.error(e);
        }
      } finally {
        if (!isCancelled) {
          const endTime = performance.now();
          setGenerationTime(endTime - startTime);
          setIsLoading(false);
        }
      }
    };

    fetchContent();
    
    return () => {
      isCancelled = true;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [currentTopic, language]);


  const handleWordClick = useCallback((word: string) => {
    const newTopic = word.trim();
    if (newTopic && newTopic.toLowerCase() !== currentTopic.toLowerCase()) {
      setCurrentTopic(newTopic);
      setIsLoading(true); // Explicitly set loading to true to trigger fetch
      setContent('');
    }
  }, [currentTopic]);

  const handleSearch = useCallback((topic: string) => {
    const newTopic = topic.trim();
    setCurrentTopic(newTopic);
    setIsLoading(true);
    setContent('');
  }, []);

  return (
    <div>
      <SearchBar 
        onSearch={handleSearch} 
        isLoading={isLoading}
        selectedLanguage={language}
        onLanguageChange={setLanguage}
      />
      
      <header style={{ textAlign: 'center', marginBottom: '2rem' }}>
        <h1 style={{ letterSpacing: '0.2em', textTransform: 'uppercase' }}>
          NEXUSWIKI
        </h1>
      </header>
      
      <main>
        <div>
          <div style={{ display: 'flex', alignItems: 'center', marginBottom: '2rem', gap: '0.5rem' }}>
            <h2 style={{ textTransform: 'capitalize', margin: 0 }}>
              {currentTopic}
            </h2>
          </div>

          {error && (
            <div style={{ border: '1px solid #cc0000', padding: '1rem', color: '#cc0000' }}>
              <p style={{ margin: 0 }}>An Error Occurred</p>
              <p style={{ marginTop: '0.5rem', margin: 0 }}>{error}</p>
            </div>
          )}
          
          {isLoading && content.length === 0 && !error && (
            <LoadingSkeleton />
          )}

          {content.length > 0 && !error && (
             <ContentDisplay 
               content={content} 
               isLoading={isLoading} 
               onWordClick={handleWordClick}
               language={language}
             />
          )}

          {!isLoading && !error && content.length === 0 && (
            <div style={{ color: '#888', padding: '2rem 0' }}>
              <p>Content could not be generated.</p>
            </div>
          )}
        </div>
      </main>

      <footer className="sticky-footer">
        <p className="footer-text" style={{ margin: 0 }}>
          NexusWiki by <a href="https://github.com/leolinpotato" target="_blank" rel="noopener noreferrer">Leo Lin</a> · Generated by Gemini 2.5 Flash
          {generationTime && ` · ${Math.round(generationTime)}ms`}
        </p>
      </footer>
    </div>
  );
};

export default App;